apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-station
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-station
  template:
    metadata:
      labels:
        app: central-station
    spec:
      containers:
        - name: central-station
          image: central-station:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: parquet-volume
              mountPath: /app/parquet/
      volumes:
        - name: parquet-volume
          hostPath:
            path: /home/amr/parquet-data
            type: DirectoryOrCreate