apiVersion: v1
kind: Service
metadata:
  name: central-station
spec:
  type: NodePort
  selector:
    app: central-station
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  
