apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"kibana","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"kibana"}},"template":{"metadata":{"labels":{"app":"kibana"}},"spec":{"containers":[{"env":[{"name":"SERVER_HOST","value":"0.0.0.0"},{"name":"ELASTICSEARCH_HOSTS","value":"http://elasticsearch:9200"}],"image":"docker.elastic.co/kibana/kibana:8.12.0","imagePullPolicy":"IfNotPresent","name":"kibana","ports":[{"containerPort":5601}]}]}}}}
  creationTimestamp: "2025-05-24T21:09:01Z"
  generation: 1
  name: kibana
  namespace: default
  resourceVersion: "10473"
  uid: 254da0ae-3f0a-47ba-8e07-b2ff741adf54
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kibana
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kibana
    spec:
      containers:
      - env:
        - name: SERVER_HOST
          value: 0.0.0.0
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch:9200
        image: docker.elastic.co/kibana/kibana:8.12.0
        imagePullPolicy: IfNotPresent
        name: kibana
        ports:
        - containerPort: 5601
          protocol: TCP
        resources: 
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-24T21:09:04Z"
    lastUpdateTime: "2025-05-24T21:09:04Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-05-24T21:09:01Z"
    lastUpdateTime: "2025-05-24T21:09:04Z"
    message: ReplicaSet "kibana-5f74f957f8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
