apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-1
  template:
    metadata:
      labels:
        app: weather-station-1
    spec:
      containers:
        - name: weather-station
          image: weather-station:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: STATION_ID
              value: "1"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-2
  template:
    metadata:
      labels:
        app: weather-station-2
    spec:
      containers:
        - name: weather-station
          image: weather-station:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: STATION_ID
              value: "2"  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-3
  template:
    metadata:
      labels:
        app: weather-station-3
    spec:
      containers:
        - name: weather-station
          image: weather-station:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: STATION_ID
              value: "3"  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-4
  template:
    metadata:
      labels:
        app: weather-station-4
    spec:
      containers:
        - name: weather-station
          image: weather-station:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: STATION_ID
              value: "4"  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-5
  template:
    metadata:
      labels:
        app: weather-station-5
    spec:
      containers:
        - name: weather-station
          image: weather-station:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: STATION_ID
              value: "5"  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-6
  template:
    metadata:
      labels:
        app: weather-station-6
    spec:
      containers:
        - name: weather-station
          image: weather-station:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: STATION_ID
              value: "6"  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-7
  template:
    metadata:
      labels:
        app: weather-station-7
    spec:
      containers:
        - name: weather-station
          image: weather-station:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: STATION_ID
              value: "7"  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-8
  template:
    metadata:
      labels:
        app: weather-station-8
    spec:
      containers:
        - name: weather-station
          image: weather-station:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: STATION_ID
              value: "8"  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-9
  template:
    metadata:
      labels:
        app: weather-station-9
    spec:
      containers:
        - name: weather-station
          image: weather-station:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: STATION_ID
              value: "9"  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-10
  template:
    metadata:
      labels:
        app: weather-station-10
    spec:
      containers:
        - name: weather-station
          image: weather-station:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: STATION_ID
              value: "10"  
